name: Deploy to AWS S3 on Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
    # This step installs dependencies
      - name: Install Dependencies and Zip
        run: npm install

      # This step zips the files
      - name: Zip Files
        run: zip -r deployment-package.zip .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      # Upload the zipped file to S3
      - name: Upload to S3
        run: aws s3 cp deployment-package.zip s3://acebook-ai-lee/
    
      # Create deployment to CodeDeploy
      - name: AWS Create Deployment
        run: |
          aws deploy create-deployment \
            --application-name lee-ai-acebook-app \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name lee-ai-acebook-deployment \
            --file-exists-behavior OVERWRITE \
            --s3-location bucket=acebook-ai-lee,key=deployment-package.zip,bundleType=zip
