name: Deploy to AWS S3 on Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
    # This step installs pip, pipenv, and our dependencies
      - name: Install Dependencies
        run: npm install
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy to S3
        run: aws s3 sync . s3://acebook-ai-lee/acebook-a-team.zip --delete

    # Create deployment to CodeDeploy
      - name: AWS Create Deployment
        run: |
          aws deploy create-deployment \
          --application-name lee-ai-acebook-app \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name lee-ai-acebook-deployment \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=acebook-ai-lee,key=acebook-a-team.zip,bundleType=zip \
            
